version: '3.1'

services:
  api:
    image: barumel/ultritium-game-server-api:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGODB_HOST: "mongo"
      MONGODB_PORT: 27017
      MONGODB_DB_NAME: "gameserver"
      MONGODB_USER: "foo"
      MONGODB_PASS: "barbaz"
      API_PORT: 8080
    volumes:
      - client-data:/srv/api/public
      - /var/run/docker.sock:/var/run/docker.sock
  client:
    image: barumel/ultritium-game-server-client:latest
    environment:
      API_URL: http://api:8080/api
    volumes:
      - client-data:/srv/client
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "foo"
      MONGO_INITDB_ROOT_PASSWORD: "barbaz"
    volumes:
      - mongo-data:/data/db

volumes:
  client-data:
  mongo-data:
